### ISSUE TITLE
Problem running image with Docker

### ISSUE THREAD

**Issue by Choogster1** [mathinstitut/goemaxima#2]
I managed to successfully build and deploy goemaxima on a test server recently using the latest version of Stack. However, now I'm trying to run it on a different server and I get the following error when I go to the URL:

"404 page not found"

I tried curl localhost and also get "404 page not found"

The image is running correctly with docker - I've tried port 80 and 8080 and I get the same error.

The docker log says: '2021/04/26 06:08:51 Info: goe handler started'

There are no logs in systemctl which are out of the ordinary.

**Comment by Lennart-Kramer** [comment]
Are you using the image from dockerhub on the server where you get the 404?

Unfortunately, we were having trouble accessing the dockerhub account so that version is slightly older.
In that version, it only accepts the `host:8080/maxima` url and not `host:8080/goemaxima`, which i guess is the problem here.
I have updated the README to reflect that and will try to update the dockerhub image soon.

Please do tell if that still does not work.

**Comment by Choogster1** [comment]
Ah, it was my fault entirely. I was just going to the basic URL and not including the subpath. I was running the image from my own build, and <server>/goemaxima works fine. Apologies for the confusion.
